# nvim startup alias
alias v="nvim"

# git aliases
alias g="git"
alias ga="git add"
alias gaa="git add --all"
alias gb="git branch" 
alias gbd="git branch --delete"
alias gbD="git branch --delete --force"
alias gcp="git cherry-pick"
alias gcpa="git cherry-pick --abort"
alias gcpc="git cherry-pick --continue"
alias gco="git checkout"
alias gcob="git checkout -b"
alias gc="git commit --verbose"
alias gcm="git commit --verbose -m"
alias gd="git diff"
alias gf="gif fetch"
alias gfo="git fetch origin"
alias gpl="git pull"
alias gps="git push"
alias gpsd="git push --dry-run"
alias gpsf="git push --force-with-lease --force-if-includes"
alias gr="git reset"
alias grs="git reset --soft"
alias grt="git restore"
alias grts="git restore --staged"
alias grm="git remove"
alias grmc="git remove --cached"
alias gs="git status"
